name = "multiquant-gold-bot"
main = "worker.js"
compatibility_date = "2026-10-02"
keep_vars = true

[observability]
enabled = true
head_sampling_rate = 1

[vars]
BOT_USERNAME = "multiquantgoldbot"
CHANNEL_USERNAME = "@multiquantacademy"
CHANNEL_CHAT_ID = "@multiquantacademy"
OKX_PUBLIC_WS_URL = "wss://ws.okx.com/ws/v5/public"
OKX_BUSINESS_WS_URL = "wss://ws.okx.com/ws/v5/business"
OKX_INST_ID = "XAU-USDT-SWAP"

[[durable_objects.bindings]]
name = "GOLD_ENGINE"
class_name = "GoldEngine"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GoldEngine"]

[triggers]
crons = ["*/1 * * * *"]
